### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/youtube-dl-expo#1]
- [ ] embed web server on expo and do IPC via http
  - https://stackoverflow.com/questions/17470090/how-to-embed-an-http-server-like-i-jetty-paw-etc-in-android-application

- [ ] download media to file system

- [x] encoding and media metadata (see https://github.com/hi-ogawa/youtube-dl-web-v2)
  - ffmpeg on wasm?

- [ ] share
  - https://expo.canny.io/feature-requests/p/share-extension-ios-share-intent-android
  - obviously share is not possible without ejecting on expo even though PWA allows "share target" nowadays...

- [ ] install expo-non-ejected app?
- [x] non-expo ipc backend for easier dev?
  - electron would be fine. then we probably won't need native webview devtools.
  - https://github.com/hi-ogawa/youtube-dl-expo/pull/3

- [x] native webview devtools
